### ISSUE TITLE
Fatal error Call to a member function toArray() 

### ISSUE THREAD

**Issue by abhigarg** [Developer-ReCap-Autodesk/Console-PHP#2]
I am getting this error for toArray()

Verifying ReCap Server connection - PHP Fatal error:  Call to a member function
toArray() on a non-object in ..\Console-PHP-master\oAuth4ReCap.php on line 153

I am trying on windows 7. I was able to run oAuthLog but when I try to create a scene by running Recap.php I am getting this error.

**Comment by cyrillef** [comment]
This error happens in the oAuth code. Which version of the oauth.dll was installed? so I can try on my end as well. One of our engineer reviewed the samples last week, so we are curious why it happened to you.

**Comment by abhigarg** [comment]
I was using following on windows 7

PHP 5.4
Oauth 1.2.2

Should I try with PHP 5.6 and Oauth 1.2.3 instead?

**Comment by cyrillef** [comment]
I installed php 5.6 VC11 x64 Thread Safe (2016-May-26 18:22:23) from http://windows.php.net/download#php-5.6
Installed php_oauth-1.2.3-5.6-ts-vc11-x64.zip from http://windows.php.net/downloads/pecl/releases/oauth/1.2.3/
Configured my php.ini file accoringly
Installed Guzzle
php -f oAuthLog.php // success
php -f ReCap.php -- -c create  // sucess

Do
php -f ReCap.php -- -h

to know all the options you can call.

After I downloaded php 5.4.9 http://windows.php.net/downloads/releases/archives/php-5.4.9-Win32-VC9-x86.zip
Installed http://windows.php.net/downloads/pecl/releases/oauth/1.2.2/php_oauth-1.2.2-5.4-ts-vc9-x86.zip

to be in the same context you were. Working fine too, so I am not sure what is your issue.

Hope that helps.

**Comment by abhigarg** [comment]
php 5.6 VC11 x64 Thread Safe and php_oauth-1.2.3-5.6-ts-vc11-x64.zip worked for me too

thanks

I will close this issue.

Can we use the auto-crop feature which is available in recap web app with this api also?

**Comment by autodesk-adn** [comment]
The API does allow you to define a bounding box, but there is no auto-crop feature yet on the API. It is a good suggestion.

**Comment by abhigarg** [comment]
I can see such an option on the recap360 web app. Its called smart crop and
user can choose to turn it on or off.

I will try to use bounding box in the meanwhile but with smart crop the
user do not have to give any input.

I can see the result was better than with the web api because of smart crop
option.

If its there on the web app then I guess it should be possible to provide
this feature on the web api also.

Or is it the case that the recap360 web app and recap web api are using
different solutions?

**Comment by cyrillef** [comment]
I understand - what I am saying is that it is not yet available in the API. I'll ask the dev team to expose it. And version 3.1 of the API runs on a different machine. Version 3.2 which is in private beta, is a different story.

**Comment by abhigarg** [comment]
Can you tell when can I expect smart crop to be released for web api?

**Comment by cyrillef** [comment]
Ok, to have autocrop you need to be on version 3.2 which is available from our Forge developer portal. Go to http://developer.autodesk.com, apply to the ReCap API to get your keys, and then the documentation will tell you how to use the new autocrop API.
